<?php
$groups = array();


//***********************************************************************
//      REAL 2014 GROUPS STARTS HERE
//************************************************************************
$groups [100] = array(
    "arrival" => "February 11, 2015",
    "created" => "February 2, 2014",
    "registered" => 1,
    "groupRatesAt" => 8,
    "compStayAt" => 12,
    "spa" => "Tucson Spa TBA",
    "citystate" => "Tucson, AZ",
    "leader" => "Cindy R.",
    "name" => "Valentine's Day Girlfriend's Getaway",
    "privacy" => "Open",
    "price" => "$$$",
    "nights" => "4+",
    "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
    "image" => "images/wonderland-big.png",
    "fbimage" => "images/sauna-fb.jpg",
    "eventbrite" => "10639640451&ref=etckt&v=2",
    "description" => "description will be posted shortly....thank you for your patience.",
    "paypal" => "NXWEEPK97ERJ2"
);
// TEST DATA WITH ACTUAL SPA NAMES STARTS HERE *****************************
// $groups [101] = array(
//     "arrival" => "April 15, 2014",
//     "created" => "Nov 1, 2012",
//     "registered" => 2,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Rancho La Puerta"."&trade;",
//     "citystate" => "Tecate, MX",
//     "leader" => "Julie Z.",
//     "name" => "New Year's Bootcamp",
//     "privacy" => "Open",
//     "price" => "$$$",
//     "nights" => "4+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/rancho-big.png",
//     "fbimage" => "images/rancho-big.png",
//     "eventbrite" => "9616201317&ref=etckt&v=2",
//     "description" => "Calling all hikers, bikers, and nature enthusiasts! We are hiking every morning and spa-ing all the rest of the day! We locked in a great deal so join us for this amazing getaway",
//     "paypal" => "NXWEEPK97ERJ2"

// );
// $groups [102] = array(
//     "arrival" => "May 1, 2014",
//     "created" => "October 15, 2013",
//     "registered" => 8,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Lake Austin Spa Resort"."&trade;",
//     "citystate" => "Lake Austin, TX",
//     "leader" => "Jane Simon",
//     "name" => "Organic Cooking Enthusiasts",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "4+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/lakeaustin-big.png",
//     "fbimage" => "images/lakeaustin-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "Yogis and yoginis welcome for this 4 night retreat to the best spa in Texas - Lake Austin Spa Resort.  With rooms overlooking the lake, we are a group of 40+ yogis.  Namaste.",
//     "paypal" => "U3QCTC3L9Z56C"

// );
// $groups [103] = array(
//     "arrival" => "March 1, 2014",
//     "created" => "December 10, 2013",
//     "registered" => 7,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Sanctuary Camelback"."&trade;",
//     "citystate" => "Scottsdale, AZ",
//     "leader" => "John B",
//     "name" => "Yoga Adventure",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "4+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/sanctuary-big.png",
//     "fbimage" => "images/sanctuary-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "A pre-holiday retreat at the best resort in Scottsdale. Zen out at the sexy Sanctuary at Camelback mountain.",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// $groups [104] = array(
//     "arrival" => "April 1, 2014",
//     "created" => "December 11, 2013",
//     "registered" => 1,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Mii Amo"."&trade;",
//     "citystate" => "Sedona, AZ",
//     "leader" => "Cathy",
//     "name" => "Silicon Beach Developers Spa Conference",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "2+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/miiamo-big.png",
//     "fbimage" => "images/miiamo-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "A retreat for accountants.  We will be meeting every morning to talk about balance sheets and income statements (just kidding).",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// $groups [105] = array(
//     "arrival" => "May 1, 2014",
//     "created" => "November 1, 2013",
//     "registered" => 7,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Red Mountain"."&trade;",
//     "citystate" => "Ivins, UT",
//     "leader" => "John B",
//     "name" => "Hiking Like a Rock Star",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "7+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/redmtn-big.png",
//     "fbimage" => "images/redmtn-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "Join us for this amazing trip to blah blah blah. The most incredible spa vacation of a lifestime! With Adam and blah blah.",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// $groups [106] = array(
//     "arrival" => "May 2, 2014",
//     "created" => "February 1, 2013",
//     "registered" => 8,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Miraval Spa Resort"."&trade;",
//     "citystate" => "Tucson, AZ",
//     "leader" => "Cindy R.",
//     "name" => "Pamper me Silly",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "2+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/miraval-big.png",
//     "fbimage" => "images/miraval-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "Join us for this amazing trip to Miraval Resort & Spa. The spa vacation of a lifestime, etc. etc. tbd",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// // TEST DATA WITH ACTUAL SPA NAMES ENDS HERE *********************

// // TEST DATA WITH FAKE SPA NAMES STARTS HERE *******************
$groups [107] = array(
    "arrival" => "March 15, 2014",
    "created" => "February 15, 2014",
    "registered" => 6,
    "groupRatesAt" => 8,
    "compStayAt" => 12,
    "spa" => "Your Favorite Spa Here"."&trade;",
    "citystate" => "Malibu, CA",
    "leader" => "Julie Z.",
    "name" => "Spa Bootcamp (example group)",
    "privacy" => "Open",
    "price" => "$$$",
    "nights" => "4+",
    "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
    "image" => "images/wonderland-big.png",
    "fbimage" => "images/sauna-fb.jpg",
    "eventbrite" => "9616201317&ref=etckt&v=2",
    "description" => "Calling all hikers, bikers, and nature enthusiasts! We are hiking every morning and spa-ing all the rest of the day! We locked in a great deal so join us for this amazing getaway",
    "paypal" => "NXWEEPK97ERJ2"
);
$groups [108] = array(
    "arrival" => "March 1, 2014",
    "created" => "October 15, 2014",
    "registered" => 8,
    "groupRatesAt" => 8,
    "compStayAt" => 12,
    "spa" => "Your Favorite Spa Here"."&trade;",
    "citystate" => "Lake Austin, TX",
    "leader" => "Jane Simon",
    "name" => "Organic Cooking Enthusiasts (example group)",
    "privacy" => "Open",
    "price" => "$$$$",
    "nights" => "4+",
    "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
    "image" => "images/wonderland-big.png",
    "fbimage" => "images/sauna-fb.jpg",
    "eventbrite" => "9616259491&ref=etckt&v=2",
    "description" => "Yogis and yoginis welcome for this 4 night retreat to the best spa in Texas - #%(&(# Spa Resort.  With rooms overlooking the lake, we are a group of 40+ yogis.  Namaste.",
    "paypal" => "U3QCTC3L9Z56C"
);
// $groups [109] = array(
//     "arrival" => "Sept 15, 2014",
//     "created" => "December 10, 2013",
//     "registered" => 7,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Malibu, CA",
//     "leader" => "John B",
//     "name" => "Yoga Adventure",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "4+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/sauna-fb.jpg",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "A pre-holiday retreat at the best resort in Scottsdale. Zen out at the sexy Sanctuary at Camelback mountain.",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// $groups [110] = array(
//     "arrival" => "Oct 15, 2014",
//     "created" => "December 11, 2013",
//     "registered" => 1,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Malibu, CA",
//     "leader" => "Cathy",
//     "name" => "Silicon Beach Developers Spa Conference",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "2+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/sauna-fb.jpg",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "A retreat for accountants.  We will be meeting every morning to talk about balance sheets and income statements (just kidding).",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// $groups [111] = array(
//     "arrival" => "Nov 15, 2014",
//     "created" => "November 1, 2013",
//     "registered" => 7,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Malibu, CA",
//     "leader" => "John B",
//     "name" => "Hiking Like a Rock Star",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "7+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/sauna-fb.jpg",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "Join us for this amazing trip to blah blah blah. The most incredible spa vacation of a lifestime! With Adam and blah blah.",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// $groups [112] = array(
//     "arrival" => "Dec 15, 2014",
//     "created" => "November 1, 2013",
//     "registered" => 8,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Malibu, CA",
//     "leader" => "John B",
//     "name" => "Pamper me Silly",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "2+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/sauna-fb.jpg",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "Join us for this amazing trip to blah blah blah. The most incredible spa vacation of a lifestime! With Adam and blah blah.",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// new 2014 groups starts here just for current dates but fake spa names
// $groups [113] = array(
//     "arrival" => "April 15, 2014",
//     "created" => "Nov 1, 2012",
//     "registered" => 2,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Tecate, MX",
//     "leader" => "Julie Z.",
//     "name" => "New Year's Bootcamp",
//     "privacy" => "Open",
//     "price" => "$$$",
//     "nights" => "4+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/wonderland-big.png",
//     "eventbrite" => "9616201317&ref=etckt&v=2",
//     "description" => "Calling all hikers, bikers, and nature enthusiasts! We are hiking every morning and spa-ing all the rest of the day! We locked in a great deal so join us for this amazing getaway",
//     "paypal" => "NXWEEPK97ERJ2"

// );
// $groups [114] = array(
//     "arrival" => "May 1, 2014",
//     "created" => "October 15, 2013",
//     "registered" => 8,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Lake Austin, TX",
//     "leader" => "Jane Simon",
//     "name" => "Organic Cooking Enthusiasts",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "4+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/wonderland-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "Yogis and yoginis welcome for this 4 night retreat to the best spa in Texas - Lake Austin Spa Resort.  With rooms overlooking the lake, we are a group of 40+ yogis.  Namaste.",
//     "paypal" => "U3QCTC3L9Z56C"

// );
// $groups [115] = array(
//     "arrival" => "March 1, 2014",
//     "created" => "December 10, 2013",
//     "registered" => 7,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Scottsdale, AZ",
//     "leader" => "John B",
//     "name" => "Yoga Adventure",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "4+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/wonderland-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "A pre-holiday retreat at the best resort in Scottsdale. Zen out at the sexy Sanctuary at Camelback mountain.",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// $groups [116] = array(
//     "arrival" => "April 1, 2014",
//     "created" => "December 11, 2013",
//     "registered" => 1,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Sedona, AZ",
//     "leader" => "Cathy",
//     "name" => "Silicon Beach Developers Spa Conference",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "2+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/wonderland-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "A retreat for accountants.  We will be meeting every morning to talk about balance sheets and income statements (just kidding).",
//     "paypal" => "NXWEEPK97ERJ2"
// );
// $groups [117] = array(
//     "arrival" => "May 1, 2014",
//     "created" => "November 1, 2013",
//     "registered" => 7,
//     "groupRatesAt" => 8,
//     "compStayAt" => 12,
//     "spa" => "Your Favorite Spa Here"."&trade;",
//     "citystate" => "Ivins, UT",
//     "leader" => "John B",
//     "name" => "Hiking Like a Rock Star",
//     "privacy" => "Open",
//     "price" => "$$$$",
//     "nights" => "7+",
//     "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
//     "image" => "images/wonderland-big.png",
//     "fbimage" => "images/wonderland-big.png",
//     "eventbrite" => "9616259491&ref=etckt&v=2",
//     "description" => "Join us for this amazing trip to blah blah blah. The most incredible spa vacation of a lifestime! With Adam and blah blah.",
//     "paypal" => "NXWEEPK97ERJ2"
// );
$groups [118] = array(
    "arrival" => "March 25, 2015",
    "created" => "November 1, 2013",
    "registered" => 8,
    "groupRatesAt" => 8,
    "compStayAt" => 12,
    "spa" => "Your Favorite Spa Here"."&trade;",
    "citystate" => "Tucson, AZ",
    "leader" => "John B",
    "name" => "Pamper me Silly (example only)",
    "privacy" => "Open",
    "price" => "$$$$",
    "nights" => "2+",
    "facebookgroup" => "<a href='https://www.facebook.com/groups/446680378774437/'>view group</a>",
    "image" => "images/wonderland-big.png",
    "fbimage" => "images/wonderland-big.png",
    "eventbrite" => "9616259491&ref=etckt&v=2",
    "description" => "This is an example group only. Please do not register for this group. ;)",
    "paypal" => "NXWEEPK97ERJ2"
);

?>

